### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GitHubUser-B** [Slotterleet/example-planet-json#1]
This is not a problem with your mod but i always wanted to know where you get those info, because everyone knows everything about the things to add to the mod. If you know, can you send the documentation for modern mods? Thanks.

**Comment by Slotterleet** [comment]
@GitHubUser-B
https://github.com/Anuken/Mindustry - the game's source code
Specifically for planets, the link is [Planet.java](https://github.com/Anuken/Mindustry/tree/v140.4/core/src/mindustry/type/Planet.java)
